// <auto-generated />
using System;
using Items.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Items.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ItemsDbContext))]
    [Migration("20260414053003_AddItemClass")]
    partial class AddItemClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Items.Domain.Entities.ItemClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllowExcessGrnPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool?>("AllowIssueIfExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTpiOverrideAtSo")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoAllocation")
                        .HasColumnType("bit");

                    b.Property<int?>("AutoAllocationOn")
                        .HasColumnType("int");

                    b.Property<bool>("BlockDispatchUntilTpiAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("BomQtyInDimensionsAndPieces")
                        .HasColumnType("bit");

                    b.Property<bool>("BomQtyInWeightLengthWithDimensions")
                        .HasColumnType("bit");

                    b.Property<int?>("CannotSellExpiredInNextDays")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryReleaseLeadTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DimensionBasedItem")
                        .HasColumnType("bit");

                    b.Property<decimal>("FastMovingThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("HeatNumberTracking")
                        .HasColumnType("bit");

                    b.Property<int?>("IgnoreDayInExpiry")
                        .HasColumnType("int");

                    b.Property<bool>("IndentMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("InventoryManaged")
                        .HasColumnType("bit");

                    b.Property<bool>("InwardNumberTracking")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("IssueMethod")
                        .HasColumnType("int");

                    b.Property<int>("ItemNature")
                        .HasColumnType("int");

                    b.Property<int?>("ItemType")
                        .HasColumnType("int");

                    b.Property<bool>("LongItem")
                        .HasColumnType("bit");

                    b.Property<bool>("MinimumProductionLogic")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinimumProductionQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NeedDimensionWiseConsumptionInBom")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedDimensionWiseStockKeeping")
                        .HasColumnType("bit");

                    b.Property<int>("OrderReleaseLeadTime")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProductionBatchMultiple")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Purchasable")
                        .HasColumnType("bit");

                    b.Property<string>("PurchaseAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PurchaseAccountGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("QcRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("Saleable")
                        .HasColumnType("bit");

                    b.Property<string>("SalesAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SalesAccountGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ShelfLifeApplicable")
                        .HasColumnType("bit");

                    b.Property<decimal>("SlowMovingThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("TpiCaptureRemarks")
                        .HasColumnType("bit");

                    b.Property<bool>("TpiCertificateMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("TpiRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("TpiTriggerStage")
                        .HasColumnType("int");

                    b.Property<int>("TraceabilityLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ValuationMethod")
                        .HasColumnType("int");

                    b.Property<bool>("WoReceiptCostingViaExtraIssue")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ItemClasses", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDuplicateNames")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowItemLevelCustomization")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTagNumberInSalesDocs")
                        .HasColumnType("bit");

                    b.Property<string>("AutoGenPrefix")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AutoGenSeparator")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("AutoGenSequenceIncrement")
                        .HasColumnType("int");

                    b.Property<int?>("AutoGenSequenceStart")
                        .HasColumnType("int");

                    b.Property<string>("AutoGenSuffix")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CcnNumberingBasis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("CopyAttachments")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyDescription")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyItemClassDefaults")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyPricingDetails")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyTaxDetails")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyTechnicalSpecs")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EcnEntryPermission")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableAutoBatchSerialGeneration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemCodeMaxLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.Property<bool>("LogItemClassOverrides")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemSettings", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UnitOfMeasures", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
