// <auto-generated />
using System;
using Items.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Items.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ItemsDbContext))]
    [Migration("20260414055349_AddItemVendorMapping")]
    partial class AddItemVendorMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Items.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllowExcessGrnPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool?>("AllowIssueIfExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTpiOverrideAtSo")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoAllocation")
                        .HasColumnType("bit");

                    b.Property<int?>("AutoAllocationOn")
                        .HasColumnType("int");

                    b.Property<int>("BaseUomId")
                        .HasColumnType("int");

                    b.Property<bool>("BlockDispatchUntilTpiAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("BomQtyInDimensionsAndPieces")
                        .HasColumnType("bit");

                    b.Property<int?>("CalibrationFrequencyUnit")
                        .HasColumnType("int");

                    b.Property<int?>("CalibrationFrequencyValue")
                        .HasColumnType("int");

                    b.Property<bool?>("CalibrationRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("CannotSellExpiredInNextDays")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ConsumptionNumberOfTimes")
                        .HasColumnType("int");

                    b.Property<int?>("ConsumptionPeriodUnit")
                        .HasColumnType("int");

                    b.Property<int?>("ConsumptionPeriodValue")
                        .HasColumnType("int");

                    b.Property<int?>("ConsumptionStartBasis")
                        .HasColumnType("int");

                    b.Property<int?>("ConsumptionType")
                        .HasColumnType("int");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryReleaseLeadTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("DimensionBasedItem")
                        .HasColumnType("bit");

                    b.Property<bool>("DiscountEligible")
                        .HasColumnType("bit");

                    b.Property<decimal>("FastMovingThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("HeatNumberTracking")
                        .HasColumnType("bit");

                    b.Property<string>("HsnSacCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IgnoreDayInExpiry")
                        .HasColumnType("int");

                    b.Property<bool>("IndentMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("InventoryManaged")
                        .HasColumnType("bit");

                    b.Property<bool>("InwardNumberTracking")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsToolConsumable")
                        .HasColumnType("bit");

                    b.Property<int>("IssueMethod")
                        .HasColumnType("int");

                    b.Property<int?>("ItemClassId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemNature")
                        .HasColumnType("int");

                    b.Property<int?>("ItemType")
                        .HasColumnType("int");

                    b.Property<bool>("KanbanItem")
                        .HasColumnType("bit");

                    b.Property<bool>("LongItem")
                        .HasColumnType("bit");

                    b.Property<int?>("MaintenanceFrequencyUnit")
                        .HasColumnType("int");

                    b.Property<int?>("MaintenanceFrequencyValue")
                        .HasColumnType("int");

                    b.Property<bool?>("MaintenanceRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaterialOfConstruction")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("MaximumCapacity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MinMassManufacturingQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("MinimumProductionLogic")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinimumProductionQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("MmfgItem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NeedDimensionWiseConsumptionInBom")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedDimensionWiseStockKeeping")
                        .HasColumnType("bit");

                    b.Property<int>("OrderReleaseLeadTime")
                        .HasColumnType("int");

                    b.Property<int?>("ParentItemId")
                        .HasColumnType("int");

                    b.Property<int?>("PostExhaustionAction")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProductionBatchMultiple")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Purchasable")
                        .HasColumnType("bit");

                    b.Property<string>("PurchaseAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PurchaseAccountGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PurchaseCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("QcRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Saleable")
                        .HasColumnType("bit");

                    b.Property<string>("SalesAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SalesAccountGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SalesPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("ShelfLifeApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SlowMovingThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("StandardWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SubContractingCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TaxPreference")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("TpiCaptureRemarks")
                        .HasColumnType("bit");

                    b.Property<bool>("TpiCertificateMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("TpiRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("TpiTriggerStage")
                        .HasColumnType("int");

                    b.Property<int>("TraceabilityLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ValuationMethod")
                        .HasColumnType("int");

                    b.Property<string>("VariantCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VariantName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("WantQrCode")
                        .HasColumnType("bit");

                    b.Property<bool>("WoReceiptCostingViaExtraIssue")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BaseUomId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ItemClassId");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemAlternateUom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPerfect")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("UomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UomId");

                    b.ToTable("ItemAlternateUoms", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AllowExcessGrnPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool?>("AllowIssueIfExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTpiOverrideAtSo")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoAllocation")
                        .HasColumnType("bit");

                    b.Property<int?>("AutoAllocationOn")
                        .HasColumnType("int");

                    b.Property<bool>("BlockDispatchUntilTpiAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("BomQtyInDimensionsAndPieces")
                        .HasColumnType("bit");

                    b.Property<bool>("BomQtyInWeightLengthWithDimensions")
                        .HasColumnType("bit");

                    b.Property<int?>("CannotSellExpiredInNextDays")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryReleaseLeadTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DimensionBasedItem")
                        .HasColumnType("bit");

                    b.Property<decimal>("FastMovingThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("HeatNumberTracking")
                        .HasColumnType("bit");

                    b.Property<int?>("IgnoreDayInExpiry")
                        .HasColumnType("int");

                    b.Property<bool>("IndentMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("InventoryManaged")
                        .HasColumnType("bit");

                    b.Property<bool>("InwardNumberTracking")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("IssueMethod")
                        .HasColumnType("int");

                    b.Property<int>("ItemNature")
                        .HasColumnType("int");

                    b.Property<int?>("ItemType")
                        .HasColumnType("int");

                    b.Property<bool>("LongItem")
                        .HasColumnType("bit");

                    b.Property<bool>("MinimumProductionLogic")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinimumProductionQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NeedDimensionWiseConsumptionInBom")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedDimensionWiseStockKeeping")
                        .HasColumnType("bit");

                    b.Property<int>("OrderReleaseLeadTime")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProductionBatchMultiple")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Purchasable")
                        .HasColumnType("bit");

                    b.Property<string>("PurchaseAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PurchaseAccountGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("QcRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("Saleable")
                        .HasColumnType("bit");

                    b.Property<string>("SalesAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SalesAccountGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ShelfLifeApplicable")
                        .HasColumnType("bit");

                    b.Property<decimal>("SlowMovingThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("TpiCaptureRemarks")
                        .HasColumnType("bit");

                    b.Property<bool>("TpiCertificateMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("TpiRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("TpiTriggerStage")
                        .HasColumnType("int");

                    b.Property<int>("TraceabilityLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ValuationMethod")
                        .HasColumnType("int");

                    b.Property<bool>("WoReceiptCostingViaExtraIssue")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ItemClasses", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemDrawing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrawingName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DrawingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Revision")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ShowInProductionBooking")
                        .HasColumnType("bit");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemDrawings", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDuplicateNames")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowItemLevelCustomization")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTagNumberInSalesDocs")
                        .HasColumnType("bit");

                    b.Property<string>("AutoGenPrefix")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AutoGenSeparator")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("AutoGenSequenceIncrement")
                        .HasColumnType("int");

                    b.Property<int?>("AutoGenSequenceStart")
                        .HasColumnType("int");

                    b.Property<string>("AutoGenSuffix")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CcnNumberingBasis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("CopyAttachments")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyDescription")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyItemClassDefaults")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyPricingDetails")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyTaxDetails")
                        .HasColumnType("bit");

                    b.Property<bool>("CopyTechnicalSpecs")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EcnEntryPermission")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableAutoBatchSerialGeneration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemCodeMaxLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.Property<bool>("LogItemClassOverrides")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemSettings", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemTechnicalSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapabilityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CapabilityValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemTechnicalSpecs", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemVendorMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Eoq")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreferredVendor")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxOrderQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Moq")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StandardLeadTimeDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.Property<string>("VendorItemCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VendorSku")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("WarrantyDuration")
                        .HasColumnType("int");

                    b.Property<int?>("WarrantyDurationUnit")
                        .HasColumnType("int");

                    b.Property<int?>("WarrantyStartBasis")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ItemId", "VendorId")
                        .IsUnique();

                    b.ToTable("ItemVendorMappings", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemVendorPricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePurchasePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("EffectivePurchasePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemVendorMappingId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("PriceValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PriceValidTo")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemVendorMappingId");

                    b.ToTable("ItemVendorPricings", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemVendorPurchaseUom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConversionRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPerfectConversion")
                        .HasColumnType("bit");

                    b.Property<int>("ItemVendorMappingId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseUomId")
                        .HasColumnType("int");

                    b.Property<decimal>("TolerancePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemVendorMappingId");

                    b.HasIndex("PurchaseUomId");

                    b.ToTable("ItemVendorPurchaseUoms", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemWarehouseThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MinThreshold")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OpeningQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OpeningRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReorderQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemWarehouseThresholds", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UnitOfMeasures", (string)null);
                });

            modelBuilder.Entity("Items.Domain.Entities.Item", b =>
                {
                    b.HasOne("Items.Domain.Entities.UnitOfMeasure", "BaseUom")
                        .WithMany()
                        .HasForeignKey("BaseUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Items.Domain.Entities.ItemClass", "ItemClass")
                        .WithMany()
                        .HasForeignKey("ItemClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Items.Domain.Entities.Item", "ParentItem")
                        .WithMany()
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUom");

                    b.Navigation("ItemClass");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemAlternateUom", b =>
                {
                    b.HasOne("Items.Domain.Entities.Item", "Item")
                        .WithMany("AlternateUoms")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Items.Domain.Entities.UnitOfMeasure", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemDrawing", b =>
                {
                    b.HasOne("Items.Domain.Entities.Item", "Item")
                        .WithMany("Drawings")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemTechnicalSpec", b =>
                {
                    b.HasOne("Items.Domain.Entities.Item", "Item")
                        .WithMany("TechnicalSpecs")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemVendorMapping", b =>
                {
                    b.HasOne("Items.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemVendorPricing", b =>
                {
                    b.HasOne("Items.Domain.Entities.ItemVendorMapping", "ItemVendorMapping")
                        .WithMany("Pricings")
                        .HasForeignKey("ItemVendorMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemVendorMapping");
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemVendorPurchaseUom", b =>
                {
                    b.HasOne("Items.Domain.Entities.ItemVendorMapping", "ItemVendorMapping")
                        .WithMany("PurchaseUoms")
                        .HasForeignKey("ItemVendorMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Items.Domain.Entities.UnitOfMeasure", "PurchaseUom")
                        .WithMany()
                        .HasForeignKey("PurchaseUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemVendorMapping");

                    b.Navigation("PurchaseUom");
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemWarehouseThreshold", b =>
                {
                    b.HasOne("Items.Domain.Entities.Item", "Item")
                        .WithMany("WarehouseThresholds")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Items.Domain.Entities.Item", b =>
                {
                    b.Navigation("AlternateUoms");

                    b.Navigation("Drawings");

                    b.Navigation("TechnicalSpecs");

                    b.Navigation("WarehouseThresholds");
                });

            modelBuilder.Entity("Items.Domain.Entities.ItemVendorMapping", b =>
                {
                    b.Navigation("Pricings");

                    b.Navigation("PurchaseUoms");
                });
#pragma warning restore 612, 618
        }
    }
}
